name: bitmedvit_training
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - _sysroot_linux-64_curr_repodata_hack=3=haa98f57_10
  - asttokens=3.0.0=pyhd8ed1ab_1
  - binutils=2.40=h1680402_0
  - binutils_impl_linux-64=2.40=h5293946_0
  - binutils_linux-64=2.40.0=hc2dff05_2
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.7.14=hbd8a1cb_0
  - cccl=2.3.2=h2c7f797_0
  - comm=0.2.2=pyhd8ed1ab_1
  - cuda-cccl=12.4.127=h06a4308_2
  - cuda-cccl_linux-64=12.4.127=h06a4308_2
  - cuda-command-line-tools=12.4.1=h06a4308_1
  - cuda-compiler=12.4.1=h6a678d5_1
  - cuda-crt-dev_linux-64=12.4.131=h06a4308_0
  - cuda-crt-tools=12.4.131=h06a4308_0
  - cuda-cudart=12.4.127=h99ab3db_0
  - cuda-cudart-dev=12.4.127=h99ab3db_0
  - cuda-cudart-dev_linux-64=12.4.127=hd681fbe_0
  - cuda-cudart-static=12.4.127=h99ab3db_0
  - cuda-cudart-static_linux-64=12.4.127=hd681fbe_0
  - cuda-cudart_linux-64=12.4.127=hd681fbe_0
  - cuda-cuobjdump=12.4.127=h6a678d5_1
  - cuda-cupti=12.4.127=h6a678d5_1
  - cuda-cupti-dev=12.4.127=h6a678d5_1
  - cuda-cuxxfilt=12.4.127=h6a678d5_1
  - cuda-driver-dev=12.4.127=h99ab3db_0
  - cuda-driver-dev_linux-64=12.4.127=hd681fbe_0
  - cuda-gdb=12.4.127=h122497a_1
  - cuda-libraries=12.4.1=h06a4308_1
  - cuda-libraries-dev=12.4.1=h06a4308_1
  - cuda-nsight=12.4.127=h06a4308_1
  - cuda-nvcc=12.4.131=h02f8991_0
  - cuda-nvcc-dev_linux-64=12.4.131=h4ee8466_0
  - cuda-nvcc-impl=12.4.131=h99ab3db_0
  - cuda-nvcc-tools=12.4.131=h99ab3db_0
  - cuda-nvcc_linux-64=12.4.131=he92618c_0
  - cuda-nvdisasm=12.4.127=h6a678d5_1
  - cuda-nvml-dev=12.4.127=h6a678d5_1
  - cuda-nvprof=12.4.127=h6a678d5_1
  - cuda-nvprune=12.4.127=h6a678d5_1
  - cuda-nvrtc=12.4.127=h99ab3db_1
  - cuda-nvrtc-dev=12.4.127=h99ab3db_1
  - cuda-nvtx=12.4.127=h6a678d5_1
  - cuda-nvvm-dev_linux-64=12.4.131=h06a4308_0
  - cuda-nvvm-impl=12.4.131=h6a678d5_0
  - cuda-nvvm-tools=12.4.131=h6a678d5_0
  - cuda-nvvp=12.4.127=h6a678d5_1
  - cuda-opencl=12.4.127=h6a678d5_0
  - cuda-opencl-dev=12.4.127=h6a678d5_0
  - cuda-profiler-api=12.4.127=h06a4308_1
  - cuda-sanitizer-api=12.4.127=h99ab3db_1
  - cuda-toolkit=12.4.1=hb982923_0
  - cuda-tools=12.4.1=h06a4308_1
  - cuda-version=12.4=hbda6634_3
  - cuda-visual-tools=12.4.1=h06a4308_1
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.8.14=py310hf71b8c6_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - expat=2.7.1=h6a678d5_0
  - fontconfig=2.14.1=h55d465d_3
  - freetype=2.13.3=h4a9f257_0
  - gcc_impl_linux-64=11.2.0=h1234567_1
  - gcc_linux-64=11.2.0=h5c386dc_2
  - gds-tools=1.9.1.3=h99ab3db_1
  - glib=2.84.2=h6a678d5_0
  - glib-tools=2.84.2=h6a678d5_0
  - gmp=6.3.0=h6a678d5_0
  - gxx_impl_linux-64=11.2.0=h1234567_1
  - gxx_linux-64=11.2.0=hc2dff05_2
  - icu=73.1=h6a678d5_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.37.0=pyh8f84b5b_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - kernel-headers_linux-64=3.10.0=h57e8cba_10
  - krb5=1.20.1=h143b758_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - libcublas=12.4.5.8=h99ab3db_1
  - libcublas-dev=12.4.5.8=h99ab3db_1
  - libcufft=11.2.1.3=h99ab3db_1
  - libcufft-dev=11.2.1.3=h99ab3db_1
  - libcufile=1.9.1.3=h99ab3db_1
  - libcufile-dev=1.9.1.3=h99ab3db_1
  - libcurand=10.3.5.147=h99ab3db_1
  - libcurand-dev=10.3.5.147=h99ab3db_1
  - libcusolver=11.6.1.9=h99ab3db_1
  - libcusolver-dev=11.6.1.9=h99ab3db_1
  - libcusparse=12.3.1.170=h99ab3db_1
  - libcusparse-dev=12.3.1.170=h99ab3db_1
  - libedit=3.1.20230828=h5eee18b_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.1.0=h767d61c_3
  - libgcc-devel_linux-64=11.2.0=h1234567_1
  - libgcc-ng=15.1.0=h69a702a_3
  - libglib=2.84.2=h37c7471_0
  - libgomp=15.1.0=h767d61c_3
  - libiconv=1.16=h5eee18b_3
  - libnpp=12.2.5.30=h99ab3db_1
  - libnpp-dev=12.2.5.30=h99ab3db_1
  - libnvfatbin=12.4.127=h7934f7d_2
  - libnvfatbin-dev=12.4.127=h7934f7d_2
  - libnvjitlink=12.4.127=h99ab3db_1
  - libnvjitlink-dev=12.4.127=h99ab3db_1
  - libnvjpeg=12.3.1.117=h6a678d5_1
  - libnvjpeg-dev=12.3.1.117=h06a4308_1
  - libpng=1.6.39=h5eee18b_0
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx=15.1.0=h8f9b012_3
  - libstdcxx-devel_linux-64=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libxkbcommon=1.9.1=h69220b7_0
  - libxml2=2.13.8=hfdd30dd_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nsight-compute=2024.1.1.4=h968f9c8_2
  - nspr=4.35=h6a678d5_0
  - nss=3.89.1=h6a678d5_0
  - ocl-icd=2.3.2=h5eee18b_1
  - openssl=3.5.1=h7b32b05_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.4=pyhd8ed1ab_1
  - pcre2=10.42=hebb0a14_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.1=pyhc872135_2
  - platformdirs=4.3.8=pyhe01879c_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - psutil=7.0.0=py310ha75aee5_0
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.10.18=h1a3bd86_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.10=2_cp310
  - pyzmq=26.2.0=py310h71f11fc_1
  - readline=8.2=h5eee18b_0
  - setuptools=78.1.1=py310h06a4308_0
  - six=1.17.0=pyhd8ed1ab_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - sysroot_linux-64=2.17=h57e8cba_10
  - tk=8.6.14=h993c535_1
  - tornado=6.5.1=py310ha75aee5_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.14.1=pyhe01879c_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=py310h06a4308_0
  - xkeyboard-config=2.44=h5eee18b_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zeromq=4.3.5=h6a678d5_0
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.3.1
      - accelerate==1.8.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.14
      - aiosignal==1.4.0
      - argparse==1.4.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - beartype==0.21.0
      - bitsandbytes==0.46.1
      - certifi==2025.7.9
      - chardet==4.0.0
      - charset-normalizer==3.4.2
      - colt5-attention==0.11.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - datasets==2.0.0
      - dill==0.3.8
      - einops==0.8.1
      - einops-exts==0.0.4
      - einx==0.3.0
      - filelock==3.18.0
      - fire==0.7.0
      - fonttools==4.58.5
      - frozendict==2.4.6
      - frozenlist==1.7.0
      - fsspec==2025.3.0
      - fvcore==0.1.5.post20221221
      - grad-cam==1.5.5
      - grpcio==1.73.1
      - hf-xet==1.1.5
      - huggingface-hub==0.33.4
      - hyper-connections==0.2.1
      - idna==2.10
      - imageio==2.37.0
      - iopath==0.1.10
      - jinja2==3.1.6
      - joblib==1.3.2
      - kiwisolver==1.4.8
      - lazy-loader==0.4
      - local-attention==1.11.1
      - loguru==0.7.3
      - mamba-ssm==2.2.5
      - markdown==3.8.2
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.3
      - mdurl==0.1.2
      - medmnist==3.0.2
      - mpmath==1.3.0
      - multidict==6.6.3
      - multiprocess==0.70.16
      - natten==0.20.1
      - networkx==3.4.2
      - ninja==1.11.1.4
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - opencv-python==4.12.0.88
      - pandas==2.3.1
      - pillow==11.3.0
      - portalocker==3.2.0
      - propcache==0.3.2
      - protobuf==6.31.1
      - pyarrow==20.0.0
      - pyparsing==3.2.3
      - pytz==2025.2
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.25.1
      - rich==14.0.0
      - safetensors==0.5.3
      - scikit-image==0.25.2
      - scikit-learn==1.5.2
      - scipy==1.15.3
      - seaborn==0.13.2
      - sympy==1.14.0
      - tabulate==0.9.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - termcolor==3.1.0
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - timm==1.0.17
      - tokenizers==0.21.2
      - torch==2.7.1
      - torchattacks==3.5.1
      - torchinfo==1.8.0
      - torchsummary==1.5.1
      - torchvision==0.22.1
      - tqdm==4.67.1
      - transformers==4.53.2
      - triton==3.3.1
      - ttach==0.0.3
      - tzdata==2025.2
      - urllib3==1.26.20
      - vector-quantize-pytorch==1.22.17
      - werkzeug==3.1.3
      - xxhash==3.5.0
      - yacs==0.1.8
      - yarl==1.20.1
      - zetascale==2.8.6
prefix: /home/miki/anaconda3/envs/iccad_2025
