name: jetson_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=51_gnu
  - bzip2=1.0.8=h998d150_6
  - ca-certificates=2025.2.25=hd43f75c_0
  - cudatoolkit=11.7.0=h254b3b0_10
  - cusparselt=0.2.0.1=h4c31269_0
  - expat=2.7.1=h419075a_0
  - ld_impl_linux-aarch64=2.40=h48e3ba3_0
  - libffi=3.4.4=h419075a_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h998d150_0
  - libxcb=1.17.0=hf66535e_0
  - ncurses=6.4=h419075a_0
  - openssl=3.0.17=h998d150_0
  - pip=25.1=pyhc872135_2
  - pthread-stubs=0.3=hfd63f10_1
  - python=3.10.18=hbb0f47a_0
  - readline=8.2=h998d150_0
  - setuptools=78.1.1=py310hd43f75c_0
  - sqlite=3.50.2=h998d150_1
  - tk=8.6.14=hb5ae6a8_1
  - wheel=0.45.1=py310hd43f75c_0
  - xorg-libx11=1.8.12=hf66535e_1
  - xorg-libxau=1.0.12=hf66535e_0
  - xorg-libxdmcp=1.1.5=hf66535e_0
  - xorg-xorgproto=2024.1=h998d150_1
  - xz=5.6.4=h998d150_1
  - zlib=1.2.13=h998d150_1
  - pip:
      - accelerate==1.9.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.14
      - aiosignal==1.4.0
      - argparse==1.4.0
      - async-timeout==5.0.1
      - attn-gym==0.0.5.dev13+g14fd5f4
      - attrs==25.3.0
      - beartype==0.21.0
      - bitlinear-cpp==0.0.0
      - bitsandbytes==0.46.1
      - blinker==1.9.0
      - blobfile==3.0.0
      - certifi==2025.7.14
      - chardet==4.0.0
      - charset-normalizer==3.4.2
      - click==8.2.1
      - colt5-attention==0.11.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - datasets==4.0.0
      - dill==0.3.8
      - einops==0.8.1
      - einops-exts==0.0.4
      - einx==0.3.0
      - filelock==3.18.0
      - fire==0.7.0
      - flask==3.1.1
      - fonttools==4.59.0
      - frozendict==2.4.6
      - frozenlist==1.7.0
      - fsspec==2025.3.0
      - fvcore==0.1.5.post20221221
      - grad-cam==1.5.5
      - hf-xet==1.1.5
      - huggingface-hub==0.33.4
      - hyper-connections==0.2.1
      - idna==2.10
      - imageio==2.37.0
      - iopath==0.1.10
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - joblib==1.3.2
      - kiwisolver==1.4.8
      - lazy-loader==0.4
      - local-attention==1.11.2
      - loguru==0.7.3
      - lxml==6.0.0
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.3
      - mdurl==0.1.2
      - medmnist==3.0.2
      - mpmath==1.3.0
      - multidict==6.6.3
      - multiprocess==0.70.16
      - natten==0.21.0
      - networkx==3.4.2
      - ninja==1.11.1.4
      - numpy==1.26.1
      - onnx==1.18.0
      - opencv-python==4.12.0.88
      - packaging==25.0
      - pandas==2.3.1
      - pillow==11.3.0
      - portalocker==3.2.0
      - propcache==0.3.2
      - protobuf==6.31.1
      - psutil==7.0.0
      - pyarrow==21.0.0
      - pycryptodomex==3.23.0
      - pygments==2.19.2
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.4
      - rich==14.0.0
      - safetensors==0.5.3
      - scikit-image==0.25.2
      - scikit-learn==1.5.2
      - scipy==1.15.3
      - sentencepiece==0.2.0
      - six==1.17.0
      - sympy==1.14.0
      - tabulate==0.9.0
      - termcolor==3.1.0
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - tiktoken==0.9.0
      - timm==1.0.18
      - tokenizers==0.21.2
      - torch==2.8.0
      - torchao==0.13.0
      - torchattacks==3.5.1
      - torchvision==0.23.0
      - tqdm==4.67.1
      - transformers==4.53.3
      - ttach==0.0.3
      - typing-extensions==4.14.1
      - tzdata==2025.2
      - urllib3==1.26.20
      - vector-quantize-pytorch==1.22.18
      - werkzeug==3.1.3
      - xformers==0.0.31.post1
      - xxhash==3.5.0
      - yacs==0.1.8
      - yarl==1.20.1
      - zetascale==2.8.6
prefix: /home/miki/miniconda3/envs/ICCAD
